### ISSUE TITLE
Install Fails (@discordjs/opus@0.3.3)

### ISSUE THREAD

**Issue by juristoeckli** [armand1m/node-grumble#2]
root@raspberrypi:/opt/intercom/3# yarn add node-grumble
yarn add v1.22.5
info No lockfile found.
[1/4] Resolving packages...
info There appears to be trouble with your network connection. Retrying...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠂ @discordjs/opus
error /opt/intercom/3/node_modules/@discordjs/opus: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments:
Directory: /opt/intercom/3/node_modules/@discordjs/opus
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.1.0
node-pre-gyp info using node@10.24.0 | linux | arm
node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp info check checked for "/opt/intercom/3/node_modules/@discordjs/opus/prebuild/node-v64-napi-v3-linux-arm-glibc-2.28/opus.node" (not found)
node-pre-gyp http GET https://github.com/discordjs/opus/releases/download/v0.3.3/opus-v0.3.3-node-v64-napi-v3-linux-arm-glibc-2.28.tar.gz
node-pre-gyp http 404 https://github.com/discordjs/opus/releases/download/v0.3.3/opus-v0.3.3-node-v64-napi-v3-linux-arm-glibc-2.28.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/discordjs/opus/releases/download/v0.3.3/opus-v0.3.3-node-v64-napi-v3-linux-arm-glibc-2.28.tar.gz
node-pre-gyp WARN Pre-built binaries not found for @discordjs/opus@0.3.3 and node@10.24.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://github.com/discordjs/opus/releases/download/v0.3.3/opus-v0.3.3-node-v64-napi-v3-linux-arm-glibc-2.28.tar.gz
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@10.24.0 | linux | arm
gyp info ok
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@10.24.0 | linux | arm
gyp info find Python using Python version 2.7.16 found at "/usr/bin/python"
gyp http GET https://nodejs.org/download/release/v10.24.0/node-v10.24.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.24.0/node-v10.24.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.24.0/SHASUMS256.txt
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: Client network socket disconnected before secure TLS connection was established
gyp ERR! stack     at TLSSocket.onConnectEnd (_tls_wrap.js:1125:19)
gyp ERR! stack     at Object.onceWrapper (events.js:286:20)
gyp ERR! stack     at TLSSocket.emit (events.js:203:15)
gyp ERR! stack     at endReadableNT (_stream_readable.js:1145:12)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Linux 5.10.17-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/opt/intercom/3/node_modules/@discordjs/opus/prebuild/node-v64-napi-v3-linux-arm-glibc-2.28/opus.node" "--module_name=opus" "--module_path=/opt/intercom/3/node_modules/@discordjs/opus/prebuild/node-v64-napi-v3-linux-arm-glibc-2.28" "--napi_version=7" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3"
gyp ERR! cwd /opt/intercom/3/node_modules/@discordjs/opus
gyp ERR! node -v v10.24.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/intercom/3/node_modules/@discordjs/opus/prebuild/node-v64-napi-v3-linux-arm-glibc-2.28/opus.node --module_name=opus --module_path=/opt/intercom/3/node_modules/@discordjs/opus/prebuild/node-v64-napi-v3-linux-arm-glibc-2.28 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/opt/intercom/3/node_modules/@discordjs/node-pre-gyp/lib/util/compile.js:72:20)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:982:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
node-pre-gyp ERR! System Linux 5.10.17-v7+
node-pre-gyp ERR! command "/usr/bin/node" "/opt/intercom/3/node_modules/@discordjs/opus/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /opt/intercom/3/node_modules/@discordjs/opus
node-pre-gyp ERR! node -v v10.24.0
node-pre-gyp ERR! node-pre-gyp -v v0.1.0
node-pre-gyp ERR! not ok
Failed to execute '/usr/bin/node /usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/opt/intercom/3/node_modules/@discordjs/opus/prebuild/node-v64-napi-v3-linux-arm-glibc-2.28/opus.node --module_name=opus --module_path=/opt/intercom/3/node_modules/@discordjs/opus/prebuild/node-v64-napi-v3-linux-arm-glibc-2.28 --napi_version=7 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3' (1)

**Comment by juristoeckli** [comment]
sorry, it was just a network Problem.
